### ISSUE TITLE
dpimport ignores update of data in the same day index

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpimport#10]
There is a problem with `dpimport` module that ignores update of data in the same day index:

| day | reftime | timeofday | weekday | actigraphy_raw | actigraphy_run_sheet | mtime | site |
| - | - | - | - | - | - | - | - |
| 1 |   |   |    | 0 | 1 | 2022-01-19 | NL |

if the above was imported before, then the following seems to be ignored on the next day:

| day | reftime | timeofday | weekday | actigraphy_raw | actigraphy_run_sheet | mtime | site |
| - | - | - | - | - | - | - | - |
| 1 |   |   |    | 1 | 1 | 2022-01-20 | NL |

This problem attributes to the absence of some EEG raw data where run sheet exists:

![image](https://user-images.githubusercontent.com/35086881/152876242-39c5dd6e-2844-4a86-819c-a34db949fcaf.png)

I have manually confirmed that both raw data and run sheet exist for `NL00022` and `NL00038`.

---

This kind of update is intrinsic to the combined pseudo-subject `NL` for tracking status of files. So is the above ignorance expected? @hre80 @justintbaker 

cc @sbouix

**Comment by tashrifbillah** [comment]
Hi @hre80, we shall appreciate your experienced opinion.

**Comment by tashrifbillah** [comment]
Idea-1:
find out the problem in dpimport, modify

Idea-2:
figure out the code for deleting previous mongoDB entry (the code must be executed from linux shell, not mongo shell), reimport

**Comment by hre80** [comment]
Hi @tashrifbillah , I would go with the idea-2. That's what we did at least to avoid this problem. Idea-1 is obviously ideal but I doubt that it is worth the effort.

**Comment by tashrifbillah** [comment]
Thank you for confirming that you have also dealt with this problem in the past, Habib.

**Comment by tashrifbillah** [comment]
The following deletions are not sufficient:
```js
db.toc.remove({"study":"NL"}}
db.toc.remove({"study":"files","subject":"NL"})
```

The latter has child collections that transpire into new dashboard:

![image](https://user-images.githubusercontent.com/35086881/152918233-aa980e9a-e372-47b6-9e56-8b51dce5b53d.png)

**Comment by tashrifbillah** [comment]
> Idea-2:
figure out the code for deleting previous mongoDB entry 

Hi Habib, can you help me with it? When data is imported to mongoDB, it is journalized in the table of contents as follows:

> { "_id" : ObjectId("62047e48c1647f23c0292c3c"), "study" : "mriqc", "subject" : "combined", "assessment" : "mriqc", ... , "collection" : "8d051eccc2a98eb4303bc62316124890ed47810c61ccde18b9d772e3ac379543", "time_units" : "day", "time_start" : 1, "time_end" : 9999, "path" : "MRI_ROOT/derivatives/quick_qc/mriqc-combined-mriqc-day1to9999.csv", "filetype" : "text/csv", "encoding" : null, "basename" : "mriqc-combined-mriqc-day1to9999.csv", "dirname" : "MRI_ROOT/derivatives/quick_qc", ... }

while the actual data is stored in `"collection" : "8d051eccc2a98eb4303bc62316124890ed47810c61ccde18b9d772e3ac379543"`. Removing entry from the table of contents is simple: `db.toc.remove({"study" : "mriqc", "subject" : "combined"})`. But that removal does not remove the aforementioned child collection. On the other hand, we cannot retain the child collection which will bring us back to square one.

Do you know the proper code for removing a collection including its children?

**Comment by tashrifbillah** [comment]
Idea:

Remove child first:

> db[ db.toc.findOne({ "study" : "mriqc", "subject" : "combined" }).collection ].remove({ })

Remove parent later:

> db.toc.remove({ "study" : "mriqc", "subject" : "combined" })

**Comment by tashrifbillah** [comment]
Children removal:

```js
let colls= db.toc.find({"study" : "files"});
let num= colls.length();
for (let i=0; i<num; i++) {
    print(db[ colls[i].collection ].remove())
}
```

This should be put in a script and executed via mongo interpreter.

**Comment by tashrifbillah** [comment]
Parents removal:

```js
let sites=["CA", "GA", "HA", "IR", "LA", "NL", "NN", "OR", "PA", "PI", "SD", "SF", "TE", "WU", "YA", "ProNET", "BM", "CP", "ME", "SG", "PRESCIENT"]
sites.forEach(s=> { print(db.toc.remove({"study":s})) })
```

**Comment by tashrifbillah** [comment]
This is how hashes are calculated:

https://github.com/AMP-SCZ/dpdash/blob/382018465fcb086f014b86ab6b5f52d7584361c6/server/routes/index.js#L455-L456

With this discovery, now we can maintain complete control over the collections. We no longer have to follow children-->parent order for deletion.

**Comment by tashrifbillah** [comment]
```js
hashes.forEach(h=> print(db[h].remove({})))
```

**Comment by tashrifbillah** [comment]
Tashrif wrote this importer recently:

https://github.com/AMP-SCZ/utility/blob/e0488cf5cad5d695cd6d989717233b783bd3af3f/dpimport_mriqc.sh#L10-L15

**Comment by tashrifbillah** [comment]
The stated issue is fixed by removing old collections before importing new ones: https://github.com/AMP-SCZ/utility/pull/5. But I am keeping this issue open because the removal I performed extrinsically should be intrinsic to dpimport. Maybe we shall have time in future to investigate it more.
